config/routes.rb
AuthM::Engine.routes.draw do
  devise_for :users, {class_name: "AuthM::User", module: :devise, path: 'auth', controllers: {confirmations: 'auth_m/users/confirmations',
                                                                                              invitations: 'auth_m/users/invitations',
                                                                                              passwords: 'auth_m/users/passwords',
                                                                                              registrations: 'auth_m/users/registrations',
                                                                                              sessions: 'auth_m/users/sessions',
                                                                                              unlocks: 'auth_m/users/unlocks',
                                                                                              omniauth_callbacks: 'auth_m/users/omniauth_callbacks' }}
  devise_scope :user do
    post "custom_sign_up" => "users/omniauth_callbacks" 
  end

  delete :unlink_account, to: 'linked_accounts#unlink'

  resources :managements, except: :index do
    post :change, on: :collection
  end

  resources :branches, except: :index do
    post :change, on: :collection
  end

  resources :public_users, except: [:new, :create]

  resources :users do
    post :impersonate, on: :member
    post :stop_impersonating, on: :collection
    put :resend_invitation, on: :member
  end

  resources :policy_groups do
    get :load_policies, on: :collection
  end
end

app/models/auth_m/ability.rb
module AuthM
  class Ability
    include AuthM::AbilityConcern
    
    # def initialize(user, branch)
    #   super
    # 
    #   if user.has_role? :user
    #   end    
    #
    #   if user.has_role? :public
    #   end
    # end

  end
end

app/models/auth_m/application_record.rb
module AuthM
  class ApplicationRecord < ActiveRecord::Base
    self.abstract_class = true
  end
end

app/models/auth_m/branch.rb
# == Schema Information
#
# Table name: auth_m_branches
#
#  id            :bigint           not null, primary key
#  name          :string(255)      not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  management_id :bigint
#
# Indexes
#
#  index_auth_m_branches_on_management_id  (management_id)
#

module AuthM
  class Branch < ApplicationRecord
    include AuthM::BranchConcern

    # Your code goes here...
    
  end
end

app/models/auth_m/branch_resource.rb
# == Schema Information
#
# Table name: auth_m_branch_resources
#
#  id                     :bigint           not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  branch_id              :bigint           not null
#  management_resource_id :bigint           not null
#
# Indexes
#
#  index_auth_m_branch_resources_on_branch_id               (branch_id)
#  index_auth_m_branch_resources_on_management_resource_id  (management_resource_id)
#

module AuthM
  class BranchResource < ApplicationRecord
    include AuthM::BranchResourceConcern  
    
    # Your code goes here...
    
  end
end

app/models/auth_m/linked_account.rb
# == Schema Information
#
# Table name: auth_m_linked_accounts
#
#  id         :bigint           not null, primary key
#  provider   :string(255)      not null
#  uid        :string(255)      not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_auth_m_linked_accounts_on_provider  (provider)
#  index_auth_m_linked_accounts_on_uid       (uid)
#  index_auth_m_linked_accounts_on_user_id   (user_id)
#

module AuthM
  class LinkedAccount < ApplicationRecord
    include AuthM::LinkedAccountConcern
    
    # Your code goes here...
    
  end
end

app/models/auth_m/management.rb
# == Schema Information
#
# Table name: auth_m_managements
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

module AuthM
  class Management < ApplicationRecord
    include AuthM::ManagementConcern

    # Your code goes here...

  end
end

app/models/auth_m/management_resource.rb
# == Schema Information
#
# Table name: auth_m_management_resources
#
#  id            :bigint           not null, primary key
#  name          :string(255)      not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  management_id :bigint           not null
#
# Indexes
#
#  index_auth_m_management_resources_on_management_id  (management_id)
#

module AuthM
  class ManagementResource < ApplicationRecord
    include AuthM::ManagementResourceConcern  
    
    # Your code goes here...
    
  end
end

app/models/auth_m/policy.rb
# == Schema Information
#
# Table name: auth_m_policies
#
#  id                 :bigint           not null, primary key
#  access             :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  branch_resource_id :bigint
#  policy_group_id    :bigint
#
# Indexes
#
#  index_auth_m_policies_on_branch_resource_id  (branch_resource_id)
#  index_auth_m_policies_on_policy_group_id     (policy_group_id)
#

module AuthM
  class Policy < ApplicationRecord
    include AuthM::PolicyConcern

    # Your code goes here...
    
  end
end

app/models/auth_m/policy_group.rb
# == Schema Information
#
# Table name: auth_m_policy_groups
#
#  id         :bigint           not null, primary key
#  customized :boolean          default(FALSE)
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  branch_id  :bigint           not null
#
# Indexes
#
#  index_auth_m_policy_groups_on_branch_id  (branch_id)
#

module AuthM
  class PolicyGroup < ApplicationRecord
    include AuthM::PolicyGroupConcern

    # Your code goes here...
    
  end
end

app/models/auth_m/policy_groups_user.rb
# == Schema Information
#
# Table name: auth_m_policy_groups_users
#
#  policy_group_id :bigint           not null
#  user_id         :bigint           not null
#
# Indexes
#
#  index_auth_m_policy_groups_users_on_policy_group_id              (policy_group_id)
#  index_auth_m_policy_groups_users_on_user_id                      (user_id)
#  index_auth_m_policy_groups_users_on_user_id_and_policy_group_id  (user_id,policy_group_id)
#

module AuthM
  class PolicyGroupsUser < ApplicationRecord
    include AuthM::PolicyGroupsUserConcern

    # Your code goes here...
    
  end
end

app/models/auth_m/user.rb
# == Schema Information
#
# Table name: auth_m_users
#
#  id                     :bigint           not null, primary key
#  active                 :boolean          default(TRUE)
#  confirmation_sent_at   :datetime
#  confirmation_token     :string(255)
#  confirmed_at           :datetime
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string(255)
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  expired_at             :datetime
#  invitation_accepted_at :datetime
#  invitation_created_at  :datetime
#  invitation_limit       :integer
#  invitation_sent_at     :datetime
#  invitation_token       :string(255)
#  invitations_count      :integer          default(0)
#  invited_by_type        :string(255)
#  last_activity_at       :datetime
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string(255)
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string(255)
#  roles_mask             :integer          not null
#  sign_in_count          :integer          default(0), not null
#  username               :string(255)      not null
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  invited_by_id          :bigint
#  management_id          :bigint
#  unique_session_id      :string(255)
#
# Indexes
#
#  index_auth_m_users_on_confirmation_token                 (confirmation_token)
#  index_auth_m_users_on_email                              (email) UNIQUE
#  index_auth_m_users_on_expired_at                         (expired_at)
#  index_auth_m_users_on_invitation_token                   (invitation_token) UNIQUE
#  index_auth_m_users_on_invitations_count                  (invitations_count)
#  index_auth_m_users_on_invited_by_id                      (invited_by_id)
#  index_auth_m_users_on_invited_by_type_and_invited_by_id  (invited_by_type,invited_by_id)
#  index_auth_m_users_on_last_activity_at                   (last_activity_at)
#  index_auth_m_users_on_management_id                      (management_id)
#  index_auth_m_users_on_reset_password_token               (reset_password_token) UNIQUE
#

module AuthM
  class User < ApplicationRecord
    include AuthM::UserConcern
    
    # Your code goes here...
    
  end
end

app/models/concerns/auth_m/ability_concern.rb
require 'active_support/concern'

module AuthM::AbilityConcern
  extend ActiveSupport::Concern
  
  included do
    include CanCan::Ability
  end

  def initialize(user, branch)
    # Define abilities for the passed in user here. For example:
    #
    user ||= AuthM::User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    if user.has_role? :root
      can :manage, :all
    end

    if user.has_role? :user
      if branch
        policy_group = user.policy_group(branch)

        if policy_group
          policy_group.policies.each do |policy|

            model = build_model(policy.resource.name)
            controller = build_controller(policy.resource.name) unless model

            if model 
              if model.reflect_on_association(:branch)
                can :"#{policy.access}", model, branch_id: branch.id
              else
                can :"#{policy.access}", model
              end
            elsif controller
              can :"#{policy.access}", :"#{controller}"
            end
          end
          
          can :change, AuthM::Branch if user.policy_groups.length > 1
        end
      end
      
      can :unlink, AuthM::LinkedAccount, user_id: user.id
      can :stop_impersonating, AuthM::User
    end

    if user.has_role? :public
      can :unlink, AuthM::LinkedAccount, user_id: user.id
    end
  end

  private

    def build_model model
      if model.include?("auth_m_") 
        model_name = model.split("auth_m_")
        model = "authM::#{model_name.last.camelcase}" 
      end

      model.camelcase.singularize.constantize rescue nil
    end

    def build_controller controller
      controller.singularize
    end
end

app/models/concerns/auth_m/branch_concern.rb
# == Schema Information
#
# Table name: auth_m_branches
#
#  id            :bigint           not null, primary key
#  name          :string(255)      not null
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  management_id :bigint
#
# Indexes
#
#  index_auth_m_branches_on_management_id  (management_id)
#

require 'active_support/concern'

module AuthM::BranchConcern
  extend ActiveSupport::Concern

  included do
    belongs_to :management

    has_many :branch_resources, dependent: :destroy
    has_many :policy_groups, dependent: :destroy

    accepts_nested_attributes_for :branch_resources, allow_destroy: true

    validates :name, presence: true, length: { maximum: 254 }, uniqueness: {scope: :management_id}
    before_save :capitalize_name
  end

  def has_the_resource_id? resource_id
    self.branch_resources.where(management_resource_id: resource_id).exists?
  end

  def resource resource_id
    self.branch_resources.where(management_resource_id: resource_id).first
  end

  def resources
    self.branch_resources.includes(:management_resource).order("auth_m_management_resources.name ASC")
  end

  def users
    AuthM::User.where(roles_mask: AuthM::User.mask_for([:root])) + self.policy_groups.includes(:users).where(auth_m_users: {management_id: self.management_id}).collect(&:users)
  end

  private 

    def capitalize_name
      self.name = self.name.capitalize
    end
  
end

app/models/concerns/auth_m/branch_resource_concern.rb
# == Schema Information
#
# Table name: auth_m_branch_resources
#
#  id                     :bigint           not null, primary key
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  branch_id              :bigint           not null
#  management_resource_id :bigint           not null
#
# Indexes
#
#  index_auth_m_branch_resources_on_branch_id               (branch_id)
#  index_auth_m_branch_resources_on_management_resource_id  (management_resource_id)
#

require 'active_support/concern'

module AuthM::BranchResourceConcern
  extend ActiveSupport::Concern
  
  included do
    belongs_to :branch
    belongs_to :management_resource

    has_one :management, through: :management_resource
    has_many :policies, inverse_of: :branch_resource, dependent: :destroy

    attr_accessor :selected

    validates :branch, presence: true
    validates :management_resource, presence: true

    validate :is_a_valid_resource?, :on => [ :create, :update ]
  end

  def name
    self.management_resource.name
  end

  private 

    def is_a_valid_resource?
      errors.add(:base, :invalid_resource) unless self.management.resources.collect(&:id).include? self.management_resource_id
    end

end

app/models/concerns/auth_m/linked_account_concern.rb
# == Schema Information
#
# Table name: auth_m_linked_accounts
#
#  id         :bigint           not null, primary key
#  provider   :string(255)      not null
#  uid        :string(255)      not null
#  user_id    :bigint           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_auth_m_linked_accounts_on_provider  (provider)
#  index_auth_m_linked_accounts_on_uid       (uid)
#  index_auth_m_linked_accounts_on_user_id   (user_id)
#

require 'active_support/concern'

module AuthM::LinkedAccountConcern
  extend ActiveSupport::Concern
  
  included do
    belongs_to :user
    
    validates :user, presence: true
    validates :provider, presence: true, length: {maximum: 254}
    validates :uid, uniqueness: true, presence: true, length: {maximum: 254}
  end

end

app/models/concerns/auth_m/management_concern.rb
# == Schema Information
#
# Table name: auth_m_managements
#
#  id         :bigint           not null, primary key
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

require 'active_support/concern'

module AuthM::ManagementConcern
  extend ActiveSupport::Concern

  included do
    has_many :management_resources, inverse_of: :management, dependent: :destroy
    has_many :branches, inverse_of: :management, dependent: :destroy
    has_many :users, dependent: :destroy

    accepts_nested_attributes_for :management_resources, allow_destroy: true
    
    validates :name, presence: true, length: { maximum: 254 }
    validates :name, uniqueness: true, on: :create
    before_save :capitalize_name
  end

  def has_the_resource_name? resource_name
    self.management_resources.any? {|h| h.name == resource_name }
  end 

  def has_the_resource_id? resource_id
    self.management_resources.any? {|h| h.id == resource_id }
  end

  def resource name 
    self.management_resources.where(name: name).first if self.has_the_resource_name? name
  end 

  def resources 
    self.management_resources.order("name ASC")
  end

  private 

    def capitalize_name
      self.name = self.name.capitalize
    end
  
end

app/models/concerns/auth_m/policy_concern.rb
# == Schema Information
#
# Table name: auth_m_policies
#
#  id                 :bigint           not null, primary key
#  access             :string(255)
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  branch_resource_id :bigint
#  policy_group_id    :bigint
#
# Indexes
#
#  index_auth_m_policies_on_branch_resource_id  (branch_resource_id)
#  index_auth_m_policies_on_policy_group_id     (policy_group_id)
#

require 'active_support/concern'

module AuthM::PolicyConcern
  extend ActiveSupport::Concern
  
  included do
    belongs_to :branch_resource
    belongs_to :policy_group

    has_one :branch, through: :branch_resource
    has_one :management, through: :branch

    USER_ACCESS = ['none','read','manage']
    
    validates :branch_resource, presence: true
    validates :policy_group, presence: true
    validates :access, inclusion: { in: ['read','manage'] }    
  end

  def resource 
    self.branch_resource
  end

end

app/views/auth_m/users/_form.html.erb
<%= form_with model: @user, local: true do |form| %>

  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %>
        prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= form.label :username %>
    <br/>
    <%= form.text_field :username, required: true %>
  </p>

  <p>
    <%= form.label :email %>
    <br/>
    <%= form.email_field :email, required: true %>
  </p>

  <% unless @user.persisted? %>
    <p><%= form.check_box "invitable", id: "check_invitable", checked: true %> invite</p>
     <div id = 'pass_fields', style = 'display:none;'>
      <p>
        <%= form.label :password %>
        <%= form.password_field :password, id: "pass" %>
      </p>
      <p>
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, id: "pass_confirmation" %>
      </p>
     </div> 
  <% end %>
  
  <p>
    <h3>Active?</h3>
    <table>
      <tr>
        <%= form.radio_button :active, 1, checked: @user.active %>
        activo
        <%= form.radio_button :active, 0, checked: !@user.active %>
        inactivo
      </tr>
    </table>
  </p>

  <p>
    <h3>Policies Group</h3>
    <p><%= select_tag :policy_group_selector, options_for_select(@option_for_select, @selected), include_blank: true, id: 'policy_group_select'%></p>

    <div id='div_policies'>
      <%= render template: 'auth_m/policy_groups/policies/index', locals: {policy_group: @policy_group} %>
    </div>
  </p>

  <p><%= form.submit %></p>

<% end %>

app/views/auth_m/users/_user.html.erb
<h1>User</h1>
<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>
<% if can? :read, AuthM::User %>
  <p>
    <strong>sign_in_count:</strong>
    <%= @user.sign_in_count %>
  </p>
  <p>
    <strong>last_sign_in_at:</strong>
    <%= @user.last_sign_in_at %>
  </p>
  <p>
    <strong>last_sign_in_ip:</strong>
    <%= @user.last_sign_in_ip %>
  </p>
  <p>
    <strong>role:</strong>
    <%= @user.role %>
  </p>
  <p>
    <strong>active?:</strong>
    <%= @user.active %>
  </p>
  <p>
    <strong>confirmed email?:</strong>
    <%= !@user.confirmed_at.nil? %>
    <%= " - #{@user.confirmed_at}" if !@user.confirmed_at.nil?  %>
  </p>
  <% unless @user.invitation_sent_at.nil? %>
    <p>
      <strong>invitation created at:</strong>
      <%= @user.invitation_created_at %>
    </p>
    <p>
      <strong>invitation sent at:</strong>
      <%= @user.invitation_sent_at %>
    </p>
    <p>
      <strong>invitation accepted at:</strong>
      <%= @user.invitation_accepted_at %>
    </p>
  <% end %>
  <% if (@user.has_role? :user) && @user.policy_group %>
    <p>      
      <h3>Policy Group</h3>
      <%= @user.policy_group.name if @user.policy_group %>
    </p>
    <p>
      <h3>Policies</h3>
      <table>
        <tr>
          <th>Resources</th>
          <th>Access</th>
          <% @user.policy_group.policies.each do |policy| %>
            <tr>
              <td>
                <%= policy.resource.name %>
              </td>
              <td>
                <%= policy.access %>
              </td>
            </tr>
          <% end %>
        </tr>
      </table>
    </p>
  <% end %>
<% end %>
<% if can? :manage, AuthM::User %>
  <%= link_to 'Sign in', auth_m.impersonate_person_user_path(@person), method: :post %>
  <%= link_to 'Edit', auth_m.edit_person_user_path(@person) %>
  <%= link_to 'Destroy', auth_m.person_user_path(@person), method: :delete, data: { confirm: 'Are you sure?' }  %>
<% end %>

app/views/auth_m/users/edit.html.erb
<h1>Edit user</h1>
<%= render partial: 'form' %>

<br>
<%= link_to 'Back', @user %>

app/views/auth_m/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>username</th>
    <th>email</th>
    <th>role</th>
    <th>policies</th>
    <th>active?</th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>      
      <td><%= user.email %></td>      
      <td><%= user.role %></td>       
      <td><%= user.policy_group(current_branch).name if user.policy_group(current_branch).present? %></td>      
      <td><%= user.active %></td>
      <td><%= link_to 'Show', user if can? :read, user %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'New', new_user_path if can? :write, AuthM::User %>

app/views/auth_m/users/new.html.erb
<h1>New User</h1>
<%= render partial: 'form' %>

<br>
<%= link_to 'Back', users_path %>

app/views/auth_m/users/show.html.erb
<h1>User</h1>

<p>
  <strong>username:</strong>
  <%= @user.username %>
</p>
<p>
  <strong>email:</strong>
  <%= @user.email %>
</p>
<p>
  <strong>registration_created_at:</strong>
  <%= @user.created_at%>
</p>  
<p>
  <strong>sign_in_count:</strong>
  <%= @user.sign_in_count %>
</p>
<p>
  <strong>last_sign_in_at:</strong>
  <%= @user.last_sign_in_at %>
</p>
<p>
  <strong>last_sign_in_ip:</strong>
  <%= @user.last_sign_in_ip %>
</p>
<p>
  <strong>role:</strong>
  <%= @user.role %>
</p>
<p>
  <strong>active?:</strong>
  <%= @user.active %>
</p>
<p>
  <strong>confirmed email?:</strong>
  <%= @user.confirmed_at %>
</p>
<p>
  <strong>invitation created at:</strong>
  <%= @user.invitation_created_at %>
</p>
<p>
  <strong>invitation sent at:</strong>
  <%= @user.invitation_sent_at %>
</p>
<p>
  <strong>invitation accepted at:</strong>
  <%= @user.invitation_accepted_at %>
</p>

<% if @policy_group %>
  <p>      
    <h3>Policy Group</h3>
    <%= @policy_group.name %>
  </p>
  <p>
    <h3>Policies</h3>
    <table>
      <tr>
        <th>Resources</th>
        <th>Access</th>
        <% @policy_group.policies.each do |policy| %>
          <tr>
            <td><%= policy.branch_resource.name %></td>
            <td><%= policy.access %></td>
          </tr>
        <% end %>
      </tr>
    </table>
  </p>
<% end %>

<%= link_to 'Resend invitation', resend_invitation_user_path(@user), method: :put if (can? :impersonate, @user) && !@user.confirmed_at %>
<%= link_to 'Sign in', impersonate_user_path(@user), method: :post if can? :impersonate, @user %>
<%= link_to 'Edit', edit_user_path(@user) if can? :write, @user %>
<%= link_to 'Destroy', @user, method: :delete, data: { confirm: 'Are you sure?' } if can? :write, @user %>

<br>
<%= link_to 'Back', users_path %>